import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "./providers";
import NavbarClient from "./components/navbar-client";

import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";

import { cookies } from "next/headers";




export const metadata: Metadata = {
  title: "Clon de twiiter",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


    
    const supabase = createServerComponentClient({cookies})
    const {data: {session}} = await supabase.auth.getSession();

    




  return (
    <html lang="en" className="dark">
      <body>
        <Providers>
          <NavbarClient session={session}/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
